### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by shawncplus** [lorry-lee/vim-ayumi#1]
No screenshots

**Comment by lorry-lee** [comment]
hi, 

Sorry I can't see any screenshots,  please send me the email with the screenshots if you wish, to help me improve it. 

lorry.le@gmail.com

thanks

lorry

**Comment by shawncplus** [comment]
I meant that you have no screenshots of your colorscheme which means people have to download it to see what it looks like which is a hassle.

**Comment by lorry-lee** [comment]
Now it's uploaded into master branch and I didn't find a good place to locate this screenshot picture in a independent website.

https://github.com/lorry-lee/vim-ayumi/blob/master/screenshot/ayumi.jpg

Sorry for the late responding but I can't upload anything in company.

Thank you for your remind :)
